// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(attestation_mobileFFI)
import attestation_mobileFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_attestation_mobile_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_attestation_mobile_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct AtomicHashResult {
    public var sha256Hex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sha256Hex: String) {
        self.sha256Hex = sha256Hex
    }
}



extension AtomicHashResult: Equatable, Hashable {
    public static func ==(lhs: AtomicHashResult, rhs: AtomicHashResult) -> Bool {
        if lhs.sha256Hex != rhs.sha256Hex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sha256Hex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAtomicHashResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AtomicHashResult {
        return
            try AtomicHashResult(
                sha256Hex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AtomicHashResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sha256Hex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtomicHashResult_lift(_ buf: RustBuffer) throws -> AtomicHashResult {
    return try FfiConverterTypeAtomicHashResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtomicHashResult_lower(_ value: AtomicHashResult) -> RustBuffer {
    return FfiConverterTypeAtomicHashResult.lower(value)
}


public struct AtomicSignedArtifact {
    public var jpgBytes: Data
    public var manifestJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(jpgBytes: Data, manifestJson: String) {
        self.jpgBytes = jpgBytes
        self.manifestJson = manifestJson
    }
}



extension AtomicSignedArtifact: Equatable, Hashable {
    public static func ==(lhs: AtomicSignedArtifact, rhs: AtomicSignedArtifact) -> Bool {
        if lhs.jpgBytes != rhs.jpgBytes {
            return false
        }
        if lhs.manifestJson != rhs.manifestJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(jpgBytes)
        hasher.combine(manifestJson)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAtomicSignedArtifact: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AtomicSignedArtifact {
        return
            try AtomicSignedArtifact(
                jpgBytes: FfiConverterData.read(from: &buf), 
                manifestJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AtomicSignedArtifact, into buf: inout [UInt8]) {
        FfiConverterData.write(value.jpgBytes, into: &buf)
        FfiConverterString.write(value.manifestJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtomicSignedArtifact_lift(_ buf: RustBuffer) throws -> AtomicSignedArtifact {
    return try FfiConverterTypeAtomicSignedArtifact.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtomicSignedArtifact_lower(_ value: AtomicSignedArtifact) -> RustBuffer {
    return FfiConverterTypeAtomicSignedArtifact.lower(value)
}


public struct C2paSignedPhoto {
    public var signedJpeg: Data
    public var manifestJson: String
    public var assetHashHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(signedJpeg: Data, manifestJson: String, assetHashHex: String) {
        self.signedJpeg = signedJpeg
        self.manifestJson = manifestJson
        self.assetHashHex = assetHashHex
    }
}



extension C2paSignedPhoto: Equatable, Hashable {
    public static func ==(lhs: C2paSignedPhoto, rhs: C2paSignedPhoto) -> Bool {
        if lhs.signedJpeg != rhs.signedJpeg {
            return false
        }
        if lhs.manifestJson != rhs.manifestJson {
            return false
        }
        if lhs.assetHashHex != rhs.assetHashHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(signedJpeg)
        hasher.combine(manifestJson)
        hasher.combine(assetHashHex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeC2paSignedPhoto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> C2paSignedPhoto {
        return
            try C2paSignedPhoto(
                signedJpeg: FfiConverterData.read(from: &buf), 
                manifestJson: FfiConverterString.read(from: &buf), 
                assetHashHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: C2paSignedPhoto, into buf: inout [UInt8]) {
        FfiConverterData.write(value.signedJpeg, into: &buf)
        FfiConverterString.write(value.manifestJson, into: &buf)
        FfiConverterString.write(value.assetHashHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeC2paSignedPhoto_lift(_ buf: RustBuffer) throws -> C2paSignedPhoto {
    return try FfiConverterTypeC2paSignedPhoto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeC2paSignedPhoto_lower(_ value: C2paSignedPhoto) -> RustBuffer {
    return FfiConverterTypeC2paSignedPhoto.lower(value)
}


public struct CaptureContext {
    public var appName: String
    public var deviceModel: String
    public var osVersion: String
    public var capturedAtIso8601: String
    public var trustLevel: String
    public var nonce: String?
    public var latitude: Double?
    public var longitude: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(appName: String, deviceModel: String, osVersion: String, capturedAtIso8601: String, trustLevel: String, nonce: String?, latitude: Double?, longitude: Double?) {
        self.appName = appName
        self.deviceModel = deviceModel
        self.osVersion = osVersion
        self.capturedAtIso8601 = capturedAtIso8601
        self.trustLevel = trustLevel
        self.nonce = nonce
        self.latitude = latitude
        self.longitude = longitude
    }
}



extension CaptureContext: Equatable, Hashable {
    public static func ==(lhs: CaptureContext, rhs: CaptureContext) -> Bool {
        if lhs.appName != rhs.appName {
            return false
        }
        if lhs.deviceModel != rhs.deviceModel {
            return false
        }
        if lhs.osVersion != rhs.osVersion {
            return false
        }
        if lhs.capturedAtIso8601 != rhs.capturedAtIso8601 {
            return false
        }
        if lhs.trustLevel != rhs.trustLevel {
            return false
        }
        if lhs.nonce != rhs.nonce {
            return false
        }
        if lhs.latitude != rhs.latitude {
            return false
        }
        if lhs.longitude != rhs.longitude {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(appName)
        hasher.combine(deviceModel)
        hasher.combine(osVersion)
        hasher.combine(capturedAtIso8601)
        hasher.combine(trustLevel)
        hasher.combine(nonce)
        hasher.combine(latitude)
        hasher.combine(longitude)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCaptureContext: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CaptureContext {
        return
            try CaptureContext(
                appName: FfiConverterString.read(from: &buf), 
                deviceModel: FfiConverterString.read(from: &buf), 
                osVersion: FfiConverterString.read(from: &buf), 
                capturedAtIso8601: FfiConverterString.read(from: &buf), 
                trustLevel: FfiConverterString.read(from: &buf), 
                nonce: FfiConverterOptionString.read(from: &buf), 
                latitude: FfiConverterOptionDouble.read(from: &buf), 
                longitude: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: CaptureContext, into buf: inout [UInt8]) {
        FfiConverterString.write(value.appName, into: &buf)
        FfiConverterString.write(value.deviceModel, into: &buf)
        FfiConverterString.write(value.osVersion, into: &buf)
        FfiConverterString.write(value.capturedAtIso8601, into: &buf)
        FfiConverterString.write(value.trustLevel, into: &buf)
        FfiConverterOptionString.write(value.nonce, into: &buf)
        FfiConverterOptionDouble.write(value.latitude, into: &buf)
        FfiConverterOptionDouble.write(value.longitude, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCaptureContext_lift(_ buf: RustBuffer) throws -> CaptureContext {
    return try FfiConverterTypeCaptureContext.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCaptureContext_lower(_ value: CaptureContext) -> RustBuffer {
    return FfiConverterTypeCaptureContext.lower(value)
}


public enum AttestationError {

    
    
    case SigningFailed(message: String)
    
    case ManifestBuildFailed(message: String)
    
    case CertificateError(message: String)
    
    case JpegEmbedFailed(message: String)
    
    case JpegValidationFailed(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAttestationError: FfiConverterRustBuffer {
    typealias SwiftType = AttestationError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AttestationError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .SigningFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .ManifestBuildFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .CertificateError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .JpegEmbedFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .JpegValidationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AttestationError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .SigningFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .ManifestBuildFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .CertificateError(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .JpegEmbedFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .JpegValidationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))

        
        }
    }
}


extension AttestationError: Equatable, Hashable {}

extension AttestationError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}


public enum SignerError {

    
    
    case HardwareUnavailable(message: String)
    
    case KeyNotFound(message: String)
    
    case SignatureOperationFailed(message: String)
    
    case CertificateExportFailed(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignerError: FfiConverterRustBuffer {
    typealias SwiftType = SignerError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignerError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .HardwareUnavailable(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .KeyNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .SignatureOperationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .CertificateExportFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SignerError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .HardwareUnavailable(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .KeyNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .SignatureOperationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .CertificateExportFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))

        
        }
    }
}


extension SignerError: Equatable, Hashable {}

extension SignerError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




public protocol HardwareSigner : AnyObject {
    
    func sign(data: Data) throws  -> Data
    
    func certificateDer() throws  -> Data
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceHardwareSigner {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceHardwareSigner = UniffiVTableCallbackInterfaceHardwareSigner(
        sign: { (
            uniffiHandle: UInt64,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceHardwareSigner.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.sign(
                     data: try FfiConverterData.lift(data)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterData.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeSignerError.lower
            )
        },
        certificateDer: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceHardwareSigner.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.certificateDer(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterData.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeSignerError.lower
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceHardwareSigner.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface HardwareSigner: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitHardwareSigner() {
    uniffi_attestation_mobile_core_fn_init_callback_vtable_hardwaresigner(&UniffiCallbackInterfaceHardwareSigner.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceHardwareSigner {
    fileprivate static var handleMap = UniffiHandleMap<HardwareSigner>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceHardwareSigner : FfiConverter {
    typealias SwiftType = HardwareSigner
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
public func buildAndSignC2pa(jpegBytes: Data, context: CaptureContext, signer: HardwareSigner)throws  -> C2paSignedPhoto {
    return try  FfiConverterTypeC2paSignedPhoto.lift(try rustCallWithError(FfiConverterTypeAttestationError.lift) {
    uniffi_attestation_mobile_core_fn_func_build_and_sign_c2pa(
        FfiConverterData.lower(jpegBytes),
        FfiConverterTypeCaptureContext.lower(context),
        FfiConverterCallbackInterfaceHardwareSigner.lower(signer),$0
    )
})
}
public func buildC2paPlaceholder(jpgBytes: Data, signatureBase64: String, metadataJson: String) -> AtomicSignedArtifact {
    return try!  FfiConverterTypeAtomicSignedArtifact.lift(try! rustCall() {
    uniffi_attestation_mobile_core_fn_func_build_c2pa_placeholder(
        FfiConverterData.lower(jpgBytes),
        FfiConverterString.lower(signatureBase64),
        FfiConverterString.lower(metadataJson),$0
    )
})
}
public func hashFrameBytes(frameBytes: Data) -> AtomicHashResult {
    return try!  FfiConverterTypeAtomicHashResult.lift(try! rustCall() {
    uniffi_attestation_mobile_core_fn_func_hash_frame_bytes(
        FfiConverterData.lower(frameBytes),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_attestation_mobile_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_attestation_mobile_core_checksum_func_build_and_sign_c2pa() != 13219) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_attestation_mobile_core_checksum_func_build_c2pa_placeholder() != 36355) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_attestation_mobile_core_checksum_func_hash_frame_bytes() != 53869) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_attestation_mobile_core_checksum_method_hardwaresigner_sign() != 25072) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_attestation_mobile_core_checksum_method_hardwaresigner_certificate_der() != 45351) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitHardwareSigner()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all